version: '1'

services:
  db:
    image: postgres:12-alpine
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_DB: efisherydemo
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:9000"
    depends_on:
      - db
    networks:
      - default